### ISSUE TITLE
Video not visible in any browser on iOS device

### ISSUE THREAD

**Issue by Cutaiar** [balataca/aframe-transparent-video-shader#14]
This shader worked great to render a `webm` video in an aframe scene on desktop (Chrome). Running the same code on mobile, the video is not visible (and there are no logs in the console indicating an issue). 

You can actually reproduce this using the Glitch demo linked in the readme: https://aframe-transparent-video.glitch.me/. Send this link to an iOS device and open in any browser (I have tested with Safari, Chrome, and the Google app). Once you tap the screen, the "Click to start playing the video." message disappears, but no video is shown.

I wonder if this has anything to do with the [caveats](https://aframe.io/docs/1.3.0/primitives/a-video.html#caveats) aframe mentions about the `a-video` primitive. If I get this to work, I'll update here.

**Comment by balataca** [comment]
Thanks for reporting this! Unfortunately, I can't reproduce/test this because I don't have any IOS devices available. I believe you're right about the caveats of a-video, so I updated the glitch with the playsinline attributes to the video and also the meta tag `<meta name="apple-mobile-web-app-capable" content="yes">`. As I said I can't test it here to see if it's fixed, but if it didn't work and you manage to figure this out, please feel free to make a Pull Request to the project, contributions are very welcomed!

**Comment by evanmcarlson** [comment]
AFAIK iOS devices do not support webm videos; you need to use HEVC encoded mp4/mov, which don't seem to work with this shader

**Comment by balataca** [comment]
Hello, thanks for reporting this issues on IOS. I decided to move this discussion to this issue:
https://github.com/balataca/aframe-transparent-video-shader/issues/18
I am working on this and hopefully we will have a solution soon for IOS devices. Also, feel free to jump into that discussion.
